name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose
        toolchain: nightly
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
        toolchain: nightly
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -Dwarnings
        toolchain: nightly
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
        toolchain: nightly
